export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'

export const ORDER_GET_REQUEST = 'ORDER_GET_REQUEST'
export const ORDER_GET_SUCCESS = 'ORDER_GET_SUCCESS'
export const ORDER_GET_FAIL = 'ORDER_GET_FAIL'

export const ORDER_GET_ALL_REQUEST = 'ORDER_GET_ALL_REQUEST'
export const ORDER_GET_ALL_SUCCESS = 'ORDER_GET_ALL_SUCCESS'
export const ORDER_GET_ALL_FAIL = 'ORDER_GET_ALL_FAIL'

export const ORDER_ADMIN_GET_ALL_REQUEST = 'ORDER_ADMIN_GET_ALL_REQUEST'
export const ORDER_ADMIN_GET_ALL_SUCCESS = 'ORDER_ADMIN_GET_ALL_SUCCESS'
export const ORDER_ADMIN_GET_ALL_FAIL = 'ORDER_ADMIN_GET_ALL_FAIL'

export const ORDER_DELIVER_REQUEST = 'ORDER_DELIVER_REQUEST'
export const ORDER_DELIVER_SUCCESS = 'ORDER_DELIVER_SUCCESS'
export const ORDER_DELIVER_FAIL = 'ORDER_DELIVER_FAIL'

export const ORDER_REMOVE_REQUEST = 'ORDER_REMOVE_REQUEST'
export const ORDER_REMOVE_SUCCESS = 'ORDER_REMOVE_SUCCESS'
export const ORDER_REMOVE_FAIL = 'ORDER_REMOVE_FAIL'
