export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'

export const PRODUCT_GET_LIST_REQUEST = 'PRODUCT_GET_LIST_REQUEST'
export const PRODUCT_GET_LIST_SUCCESS = 'PRODUCT_GET_LIST_SUCCESS'
export const PRODUCT_GET_LIST_FAIL = 'PRODUCT_GET_LIST_FAIL'

export const PRODUCT_ADD_REQUEST = 'PRODUCT_ADD_REQUEST'
export const PRODUCT_ADD_SUCCESS = 'PRODUCT_ADD_SUCCESS'
export const PRODUCT_ADD_FAIL = 'PRODUCT_ADD_FAIL'

export const PRODUCT_REMOVE_REQUEST = 'PRODUCT_REMOVE_REQUEST'
export const PRODUCT_REMOVE_SUCCESS = 'PRODUCT_REMOVE_SUCCESS'
export const PRODUCT_REMOVE_FAIL = 'PRODUCT_REMOVE_FAIL'

export const PRODUCT_REVIEW_REQUEST = 'PRODUCT_REVIEW_REQUEST'
export const PRODUCT_REVIEW_SUCCESS = 'PRODUCT_REVIEW_SUCCESS'
export const PRODUCT_REVIEW_FAIL = 'PRODUCT_REVIEW_FAIL'

export const PRODUCT_APPLY_FILTER = 'PRODUCT_APPLY_FILTER'
